openapi: 3.0.3
info:
  title: Medical Union Front - API (draft)
  version: '0.1.0'
paths:
  /api/referrals:
    get:
      summary: Get referral list
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: pageSize
          in: query
          schema:
            type: integer
        - name: q
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, accepted, rejected, all]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferralListResponse'
  /api/referrals/{id}:
    get:
      summary: Get referral by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferralResponse'
  /api/referrals/{id}/status:
    post:
      summary: Update referral status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [accepted, rejected]
                note:
                  type: string
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferralResponse'
  /api/dashboard/summary:
    get:
      summary: Get dashboard summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardSummaryResponse'
components:
  schemas:
    ReferralSummary:
      type: object
      properties:
        id:
          type: string
        patientId:
          type: string
          nullable: true
        patientName:
          type: string
        fromHospital:
          type: string
        toHospital:
          type: string
        direction:
          type: string
          enum: [inbound, outbound]
        status:
          type: string
          enum: [pending, accepted, rejected]
        note:
          type: string
          nullable: true
        handledBy:
          type: string
          nullable: true
        handledAt:
          type: string
          nullable: true
        createdAt:
          type: string
    ReferralListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ReferralSummary'
            total:
              type: integer
    ReferralResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/ReferralSummary'
    DashboardSummaryResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
          properties:
            totalReferrals:
              type: integer
            pending:
              type: integer
            accepted:
              type: integer
            rejected:
              type: integer
            todayNew:
              type: integer
            myPending:
              type: integer
